/*====================================================
Question 1
Total revenue generated by male vs. female customers
====================================================*/

SELECT gender,
COUNT(*) AS total_order,
SUM(purchase_amount) AS total_revenue
FROM shopping_behavior_cleaned
GROUP BY gender
ORDER BY total_revenue DESC;


/*====================================================
Question 2
Customers who used a discount but still spent more than the average purchase amounts
====================================================*/

SELECT
    customer_id, age, gender, item_purchased, purchase_amount, discount_applied
FROM shopping_behavior_cleaned
WHERE discount_applied = 'Yes'
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM shopping_behavior_cleaned)
ORDER BY purchase_amount DESC;


/*====================================================
Question 3
Top 5 products with the highest average review rating
====================================================*/
SELECT
    item_purchased,
    COUNT(*) AS times_purchased,
    ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM shopping_behavior_cleaned
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;


/*====================================================
Question 4
Average Purchase Amount: Standard vs. Express Shipping
====================================================*/

SELECT
    shipping_type,
    COUNT(*) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM shopping_behavior_cleaned
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


/*====================================================
Question 5
Do subscribed customers spend more?
====================================================*/

SELECT
    subscription_status,
    COUNT(*) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM shopping_behavior_cleaned
GROUP BY subscription_status;


/*====================================================
Question 6
Top 5 products with the highest % of purchases with discount applied
====================================================*/
SELECT
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 1) AS discount_pct
FROM shopping_behavior_cleaned
GROUP BY item_purchased
ORDER BY discount_pct DESC, total_purchases DESC
LIMIT 5;


/*====================================================
Question 7
Segment customers into New, Returning, Loyal (by previous_purchases), with counts
====================================================*/
SELECT
    CASE
        WHEN previous_purchases <= 17 THEN 'New'
        WHEN previous_purchases <= 33 THEN 'Returning'
        ELSE 'Loyal'
    END AS purchase_segment,
    COUNT(*) AS customer_count
FROM shopping_behavior_cleaned
GROUP BY purchase_segment
ORDER BY FIELD(purchase_segment, 'New', 'Returning', 'Loyal');


/*====================================================
Question 8
Top 3 most purchased products within each category
====================================================*/
SELECT category, item_purchased, purchase_count, rnk
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
    FROM shopping_behavior_cleaned
    GROUP BY category, item_purchased
) ranked
WHERE rnk <= 3
ORDER BY category, rnk;


/*====================================================
Question 9
Are repeat buyers (>5 previous purchases) more likely to subscribe?
====================================================*/
SELECT
    CASE WHEN previous_purchases > 5 THEN 'Repeat Buyer (>5)' ELSE 'New Buyer (<=5)' END AS buyer_type,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribed_count,
    ROUND(100 * SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 1) AS subscription_rate_pct
FROM shopping_behavior_cleaned
GROUP BY buyer_type;


/*====================================================
Question 10
Revenue contribution of each age group
====================================================*/
SELECT
    age_group,
    COUNT(*) AS total_orders,
    SUM(purchase_amount) AS total_revenue,
    ROUND(100 * SUM(purchase_amount) / (SELECT SUM(purchase_amount) FROM shopping_behavior_cleaned), 1) AS pct_of_total_revenue
FROM shopping_behavior_cleaned
GROUP BY age_group
ORDER BY total_revenue DESC;


























